backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.html"
        label: "Home Page"
        name: "index"
        fields:
          - {label: "Server Rules", name: "rules", widget: "text"}
          - {label: "IP Address", name: "ip", widget: "string"}
